name: CI
on:
  [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
    strategy:
      matrix:
        version: ["3.2.2"]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true
      - name: Set up bundler
        run: gem install bundler
      - name: Run bundle install
        run: bundle install --jobs=4
      - name: Rubocop
        run: bundle exec rubocop -c .rubocop.yml
      - name: Set up Database
        env:
          RAILS_ENV: test
        run: bundle exec rake db:setup
      - name: Test
        env:
          RAILS_ENV: test
        run: bundle exec rspec
